In [3]:
import pandas as pd
from scipy import stats 
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import statsmodels.api as sm 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import datasets,linear_model,metrics
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression

In [4]:
data=pd.read_csv("C:/Users/sudarson.SUDARSON/Downloads/Boston.csv")

In [5]:
data.head()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [6]:
data.isnull().sum()

Unnamed: 0    0
crim          0
zn            0
indus         0
chas          0
nox           0
rm            0
age           0
dis           0
rad           0
tax           0
ptratio       0
black         0
lstat         0
medv          0
dtype: int64

In [7]:
data.shape

(506, 15)

In [8]:
train,test=train_test_split(data,test_size=0.2)

In [9]:
display(train,test)

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
147,148,2.36862,0.0,19.58,0,0.871,4.926,95.7,1.4608,5,403,14.7,391.71,29.53,14.6
265,266,0.76162,20.0,3.97,0,0.647,5.560,62.8,1.9865,5,264,13.0,392.40,10.45,22.8
421,422,7.02259,0.0,18.10,0,0.718,6.006,95.3,1.8746,24,666,20.2,319.98,15.70,14.2
32,33,1.38799,0.0,8.14,0,0.538,5.950,82.0,3.9900,4,307,21.0,232.60,27.71,13.2
356,357,8.98296,0.0,18.10,1,0.770,6.212,97.4,2.1222,24,666,20.2,377.73,17.60,17.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,0.20608,22.0,5.86,0,0.431,5.593,76.5,7.9549,7,330,19.1,372.49,12.50,17.6
354,355,0.04301,80.0,1.91,0,0.413,5.663,21.9,10.5857,4,334,22.0,382.80,8.05,18.2
361,362,3.83684,0.0,18.10,0,0.770,6.251,91.1,2.2955,24,666,20.2,350.65,14.19,19.9
248,249,0.16439,22.0,5.86,0,0.431,6.433,49.1,7.8265,7,330,19.1,374.71,9.52,24.5
155,156,3.53501,0.0,19.58,1,0.871,6.152,82.6,1.7455,5,403,14.7,88.01,15.02,15.6

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
12,13,0.09378,12.5,7.87,0,0.524,5.889,39.0,5.4509,5,311,15.2,390.50,15.71,21.7
73,74,0.19539,0.0,10.81,0,0.413,6.245,6.2,5.2873,4,305,19.2,377.17,7.54,23.4
298,299,0.06466,70.0,2.24,0,0.400,6.345,20.1,7.8278,5,358,14.8,368.24,4.97,22.5
317,318,0.24522,0.0,9.90,0,0.544,5.782,71.7,4.0317,4,304,18.4,396.90,15.94,19.8
221,222,0.40771,0.0,6.20,1,0.507,6.164,91.3,3.0480,8,307,17.4,395.24,21.46,21.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,384,7.99248,0.0,18.10,0,0.700,5.520,100.0,1.5331,24,666,20.2,396.90,24.56,12.3
290,291,0.03502,80.0,4.95,0,0.411,6.861,27.9,5.1167,4,245,19.2,396.90,3.33,28.5
455,456,4.75237,0.0,18.10,0,0.713,6.525,86.5,2.4358,24,666,20.2,50.92,18.13,14.1
161,162,1.46336,0.0,19.58,0,0.605,7.489,90.8,1.9709,5,403,14.7,374.43,1.73,50.0
79,80,0.08387,0.0,12.83,0,0.437,5.874,36.6,4.5026,5,398,18.7,396.06,9.10,20.3

In [10]:
trainx,testx,trainy,testy=train.lstat,test.lstat,train.medv,test.medv

In [11]:
reg = linear_model.LinearRegression()

In [12]:
reg.score(trainx,trainy)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
trainx,textx,trainy,testy = train.iloc[0:,0:14],test.iloc[0:,0:14],train.medv,test.medv

In [ ]:
model=LinearRegression()
model.fit(trainx,trainy)

In [ ]:
model.score(testx,testy)