In [1]:
import pandas as pd
from scipy import stats 
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import statsmodels.api as sm 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import datasets,linear_model,metrics
from sklearn.metrics import mean_squared_error,confusion_matrix
from sklearn.linear_model import LogisticRegression

In [2]:
data=pd.read_csv("C:/Users/sudarson.SUDARSON/Downloads/titanic_dataset.csv")

In [3]:
data.drop(["Cabin","Ticket"],axis=1,inplace=True)

In [4]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S

In [5]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
dtype: int64

In [6]:
data.Age.fillna(data.Age.median(),inplace=True)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Fare         891 non-null    float64
 9   Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

In [8]:
data.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [9]:
data.Embarked.fillna(data.Embarked.mode().max(),inplace=True)

In [10]:
y=data.Survived

In [12]:
x=data.iloc[0:,[0,2,5,6,7,8]]
x

     PassengerId  Pclass   Age  SibSp  Parch     Fare
0              1       3  22.0      1      0   7.2500
1              2       1  38.0      1      0  71.2833
2              3       3  26.0      0      0   7.9250
3              4       1  35.0      1      0  53.1000
4              5       3  35.0      0      0   8.0500
..           ...     ...   ...    ...    ...      ...
886          887       2  27.0      0      0  13.0000
887          888       1  19.0      0      0  30.0000
888          889       3  28.0      1      2  23.4500
889          890       1  26.0      0      0  30.0000
890          891       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [13]:
trainx,testx,trainy,testy=train_test_split(x,y,test_size=0.2)

In [14]:
clf=LogisticRegression(random_state=0).fit(trainx,trainy)

C:\Users\sudarson.SUDARSON\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
predict=clf.predict(testx)
predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0], dtype=int64)

In [16]:
prob=clf.predict_proba(testx)
prob

array([[0.5726908 , 0.4273092 ],
       [0.63796015, 0.36203985],
       [0.59325658, 0.40674342],
       [0.59038241, 0.40961759],
       [0.61851512, 0.38148488],
       [0.63852065, 0.36147935],
       [0.6200398 , 0.3799602 ],
       [0.66664466, 0.33335534],
       [0.60023397, 0.39976603],
       [0.630927  , 0.369073  ],
       [0.64018204, 0.35981796],
       [0.53471137, 0.46528863],
       [0.58772467, 0.41227533],
       [0.42780982, 0.57219018],
       [0.61264102, 0.38735898],
       [0.64026704, 0.35973296],
       [0.57257574, 0.42742426],
       [0.59371791, 0.40628209],
       [0.66624922, 0.33375078],
       [0.593255  , 0.406745  ],
       [0.64357322, 0.35642678],
       [0.63359848, 0.36640152],
       [0.58818203, 0.41181797],
       [0.68525843, 0.31474157],
       [0.54792819, 0.45207181],
       [0.68632375, 0.31367625],
       [0.61584632, 0.38415368],
       [0.60898492, 0.39101508],
       [0.59356459, 0.40643541],
       [0.61010126, 0.38989874],
       [0.58655542, 0.41344458],
       [0.66343541, 0.33656459],
       [0.66982674, 0.33017326],
       [0.63307025, 0.36692975],
       [0.55654926, 0.44345074],
       [0.56069594, 0.43930406],
       [0.65757027, 0.34242973],
       [0.50690133, 0.49309867],
       [0.57920347, 0.42079653],
       [0.59520199, 0.40479801],
       [0.65220889, 0.34779111],
       [0.62634095, 0.37365905],
       [0.5904141 , 0.4095859 ],
       [0.41843895, 0.58156105],
       [0.43335252, 0.56664748],
       [0.59938778, 0.40061222],
       [0.63569608, 0.36430392],
       [0.53223256, 0.46776744],
       [0.52258094, 0.47741906],
       [0.56878027, 0.43121973],
       [0.6490437 , 0.3509563 ],
       [0.43758853, 0.56241147],
       [0.60956423, 0.39043577],
       [0.62940682, 0.37059318],
       [0.57804517, 0.42195483],
       [0.63445072, 0.36554928],
       [0.61923656, 0.38076344],
       [0.60928231, 0.39071769],
       [0.62253524, 0.37746476],
       [0.64962981, 0.35037019],
       [0.63549307, 0.36450693],
       [0.51794932, 0.48205068],
       [0.59769627, 0.40230373],
       [0.59928189, 0.40071811],
       [0.60875334, 0.39124666],
       [0.57321947, 0.42678053],
       [0.63022722, 0.36977278],
       [0.6205636 , 0.3794364 ],
       [0.60639984, 0.39360016],
       [0.63404971, 0.36595029],
       [0.62375296, 0.37624704],
       [0.6328629 , 0.3671371 ],
       [0.44648311, 0.55351689],
       [0.60611799, 0.39388201],
       [0.61929733, 0.38070267],
       [0.580764  , 0.419236  ],
       [0.66098259, 0.33901741],
       [0.56185989, 0.43814011],
       [0.60060063, 0.39939937],
       [0.63341289, 0.36658711],
       [0.60412828, 0.39587172],
       [0.58723317, 0.41276683],
       [0.57652978, 0.42347022],
       [0.61971233, 0.38028767],
       [0.62270316, 0.37729684],
       [0.35137664, 0.64862336],
       [0.63570779, 0.36429221],
       [0.55300594, 0.44699406],
       [0.60719916, 0.39280084],
       [0.6286645 , 0.3713355 ],
       [0.61890477, 0.38109523],
       [0.34853304, 0.65146696],
       [0.5665157 , 0.4334843 ],
       [0.63011817, 0.36988183],
       [0.57657696, 0.42342304],
       [0.64661161, 0.35338839],
       [0.51560153, 0.48439847],
       [0.62914337, 0.37085663],
       [0.61345621, 0.38654379],
       [0.62871723, 0.37128277],
       [0.63530139, 0.36469861],
       [0.58294196, 0.41705804],
       [0.62778945, 0.37221055],
       [0.61930727, 0.38069273],
       [0.61838093, 0.38161907],
       [0.6239326 , 0.3760674 ],
       [0.64781324, 0.35218676],
       [0.63255116, 0.36744884],
       [0.41368722, 0.58631278],
       [0.6091541 , 0.3908459 ],
       [0.63146157, 0.36853843],
       [0.66717235, 0.33282765],
       [0.63016467, 0.36983533],
       [0.58926344, 0.41073656],
       [0.61455374, 0.38544626],
       [0.68794908, 0.31205092],
       [0.62851339, 0.37148661],
       [0.67003444, 0.32996556],
       [0.61983871, 0.38016129],
       [0.58638398, 0.41361602],
       [0.60656088, 0.39343912],
       [0.54752012, 0.45247988],
       [0.68114581, 0.31885419],
       [0.62431641, 0.37568359],
       [0.63747182, 0.36252818],
       [0.61249036, 0.38750964],
       [0.53290898, 0.46709102],
       [0.63820594, 0.36179406],
       [0.63861987, 0.36138013],
       [0.55905126, 0.44094874],
       [0.61793239, 0.38206761],
       [0.70014896, 0.29985104],
       [0.58122323, 0.41877677],
       [0.56812953, 0.43187047],
       [0.61042918, 0.38957082],
       [0.55629763, 0.44370237],
       [0.60292041, 0.39707959],
       [0.56247437, 0.43752563],
       [0.57701533, 0.42298467],
       [0.57227264, 0.42772736],
       [0.5771156 , 0.4228844 ],
       [0.52175202, 0.47824798],
       [0.62911306, 0.37088694],
       [0.44902833, 0.55097167],
       [0.59489073, 0.40510927],
       [0.64371038, 0.35628962],
       [0.47738042, 0.52261958],
       [0.60048933, 0.39951067],
       [0.61444764, 0.38555236],
       [0.66547806, 0.33452194],
       [0.63844703, 0.36155297],
       [0.69123068, 0.30876932],
       [0.59284488, 0.40715512],
       [0.62723269, 0.37276731],
       [0.61994171, 0.38005829],
       [0.4459319 , 0.5540681 ],
       [0.63267413, 0.36732587],
       [0.61633704, 0.38366296],
       [0.68852722, 0.31147278],
       [0.58092774, 0.41907226],
       [0.65876472, 0.34123528],
       [0.71358602, 0.28641398],
       [0.58419428, 0.41580572],
       [0.62230029, 0.37769971],
       [0.61050834, 0.38949166],
       [0.60245772, 0.39754228],
       [0.45664071, 0.54335929],
       [0.46801712, 0.53198288],
       [0.59135368, 0.40864632],
       [0.47994515, 0.52005485],
       [0.57105771, 0.42894229],
       [0.58368355, 0.41631645],
       [0.60195755, 0.39804245],
       [0.62864348, 0.37135652],
       [0.41935161, 0.58064839],
       [0.62051582, 0.37948418],
       [0.6584759 , 0.3415241 ],
       [0.54676115, 0.45323885],
       [0.57266621, 0.42733379]])

In [17]:
clf.predict_proba(testx)

array([[0.5726908 , 0.4273092 ],
       [0.63796015, 0.36203985],
       [0.59325658, 0.40674342],
       [0.59038241, 0.40961759],
       [0.61851512, 0.38148488],
       [0.63852065, 0.36147935],
       [0.6200398 , 0.3799602 ],
       [0.66664466, 0.33335534],
       [0.60023397, 0.39976603],
       [0.630927  , 0.369073  ],
       [0.64018204, 0.35981796],
       [0.53471137, 0.46528863],
       [0.58772467, 0.41227533],
       [0.42780982, 0.57219018],
       [0.61264102, 0.38735898],
       [0.64026704, 0.35973296],
       [0.57257574, 0.42742426],
       [0.59371791, 0.40628209],
       [0.66624922, 0.33375078],
       [0.593255  , 0.406745  ],
       [0.64357322, 0.35642678],
       [0.63359848, 0.36640152],
       [0.58818203, 0.41181797],
       [0.68525843, 0.31474157],
       [0.54792819, 0.45207181],
       [0.68632375, 0.31367625],
       [0.61584632, 0.38415368],
       [0.60898492, 0.39101508],
       [0.59356459, 0.40643541],
       [0.61010126, 0.38989874],
       [0.58655542, 0.41344458],
       [0.66343541, 0.33656459],
       [0.66982674, 0.33017326],
       [0.63307025, 0.36692975],
       [0.55654926, 0.44345074],
       [0.56069594, 0.43930406],
       [0.65757027, 0.34242973],
       [0.50690133, 0.49309867],
       [0.57920347, 0.42079653],
       [0.59520199, 0.40479801],
       [0.65220889, 0.34779111],
       [0.62634095, 0.37365905],
       [0.5904141 , 0.4095859 ],
       [0.41843895, 0.58156105],
       [0.43335252, 0.56664748],
       [0.59938778, 0.40061222],
       [0.63569608, 0.36430392],
       [0.53223256, 0.46776744],
       [0.52258094, 0.47741906],
       [0.56878027, 0.43121973],
       [0.6490437 , 0.3509563 ],
       [0.43758853, 0.56241147],
       [0.60956423, 0.39043577],
       [0.62940682, 0.37059318],
       [0.57804517, 0.42195483],
       [0.63445072, 0.36554928],
       [0.61923656, 0.38076344],
       [0.60928231, 0.39071769],
       [0.62253524, 0.37746476],
       [0.64962981, 0.35037019],
       [0.63549307, 0.36450693],
       [0.51794932, 0.48205068],
       [0.59769627, 0.40230373],
       [0.59928189, 0.40071811],
       [0.60875334, 0.39124666],
       [0.57321947, 0.42678053],
       [0.63022722, 0.36977278],
       [0.6205636 , 0.3794364 ],
       [0.60639984, 0.39360016],
       [0.63404971, 0.36595029],
       [0.62375296, 0.37624704],
       [0.6328629 , 0.3671371 ],
       [0.44648311, 0.55351689],
       [0.60611799, 0.39388201],
       [0.61929733, 0.38070267],
       [0.580764  , 0.419236  ],
       [0.66098259, 0.33901741],
       [0.56185989, 0.43814011],
       [0.60060063, 0.39939937],
       [0.63341289, 0.36658711],
       [0.60412828, 0.39587172],
       [0.58723317, 0.41276683],
       [0.57652978, 0.42347022],
       [0.61971233, 0.38028767],
       [0.62270316, 0.37729684],
       [0.35137664, 0.64862336],
       [0.63570779, 0.36429221],
       [0.55300594, 0.44699406],
       [0.60719916, 0.39280084],
       [0.6286645 , 0.3713355 ],
       [0.61890477, 0.38109523],
       [0.34853304, 0.65146696],
       [0.5665157 , 0.4334843 ],
       [0.63011817, 0.36988183],
       [0.57657696, 0.42342304],
       [0.64661161, 0.35338839],
       [0.51560153, 0.48439847],
       [0.62914337, 0.37085663],
       [0.61345621, 0.38654379],
       [0.62871723, 0.37128277],
       [0.63530139, 0.36469861],
       [0.58294196, 0.41705804],
       [0.62778945, 0.37221055],
       [0.61930727, 0.38069273],
       [0.61838093, 0.38161907],
       [0.6239326 , 0.3760674 ],
       [0.64781324, 0.35218676],
       [0.63255116, 0.36744884],
       [0.41368722, 0.58631278],
       [0.6091541 , 0.3908459 ],
       [0.63146157, 0.36853843],
       [0.66717235, 0.33282765],
       [0.63016467, 0.36983533],
       [0.58926344, 0.41073656],
       [0.61455374, 0.38544626],
       [0.68794908, 0.31205092],
       [0.62851339, 0.37148661],
       [0.67003444, 0.32996556],
       [0.61983871, 0.38016129],
       [0.58638398, 0.41361602],
       [0.60656088, 0.39343912],
       [0.54752012, 0.45247988],
       [0.68114581, 0.31885419],
       [0.62431641, 0.37568359],
       [0.63747182, 0.36252818],
       [0.61249036, 0.38750964],
       [0.53290898, 0.46709102],
       [0.63820594, 0.36179406],
       [0.63861987, 0.36138013],
       [0.55905126, 0.44094874],
       [0.61793239, 0.38206761],
       [0.70014896, 0.29985104],
       [0.58122323, 0.41877677],
       [0.56812953, 0.43187047],
       [0.61042918, 0.38957082],
       [0.55629763, 0.44370237],
       [0.60292041, 0.39707959],
       [0.56247437, 0.43752563],
       [0.57701533, 0.42298467],
       [0.57227264, 0.42772736],
       [0.5771156 , 0.4228844 ],
       [0.52175202, 0.47824798],
       [0.62911306, 0.37088694],
       [0.44902833, 0.55097167],
       [0.59489073, 0.40510927],
       [0.64371038, 0.35628962],
       [0.47738042, 0.52261958],
       [0.60048933, 0.39951067],
       [0.61444764, 0.38555236],
       [0.66547806, 0.33452194],
       [0.63844703, 0.36155297],
       [0.69123068, 0.30876932],
       [0.59284488, 0.40715512],
       [0.62723269, 0.37276731],
       [0.61994171, 0.38005829],
       [0.4459319 , 0.5540681 ],
       [0.63267413, 0.36732587],
       [0.61633704, 0.38366296],
       [0.68852722, 0.31147278],
       [0.58092774, 0.41907226],
       [0.65876472, 0.34123528],
       [0.71358602, 0.28641398],
       [0.58419428, 0.41580572],
       [0.62230029, 0.37769971],
       [0.61050834, 0.38949166],
       [0.60245772, 0.39754228],
       [0.45664071, 0.54335929],
       [0.46801712, 0.53198288],
       [0.59135368, 0.40864632],
       [0.47994515, 0.52005485],
       [0.57105771, 0.42894229],
       [0.58368355, 0.41631645],
       [0.60195755, 0.39804245],
       [0.62864348, 0.37135652],
       [0.41935161, 0.58064839],
       [0.62051582, 0.37948418],
       [0.6584759 , 0.3415241 ],
       [0.54676115, 0.45323885],
       [0.57266621, 0.42733379]])

In [18]:
df=pd.DataFrame(prob)

In [19]:
confusion_matrix(testy,predict)

array([[104,   7],
       [ 60,   8]], dtype=int64)